name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt || true
      - run: pip install pytest pip-audit bandit cyclonedx-bom || true
      - run: pytest -q || true
      - run: pip-audit --fail-on high || true
      - run: bandit -r . || true
      - run: cyclonedx-bom -o bom.xml || true
      - uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: bom.xml
