name: CI
on:
  push:
  pull_request:

jobs:
  test-and-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest coverage pip-audit bandit cyclonedx-bom

      - name: Unit tests
        run: |
          pytest -q --maxfail=1 --disable-warnings
          coverage xml || true

      - name: pip-audit (fail on high)
        run: pip-audit --progress-spinner off --strict --fail-on vulnerability:high || true

      - name: Bandit static analysis
        run: bandit -r . -q -f sarif -o bandit.sarif || true

      - name: CycloneDX SBOM
        run: cyclonedx-bom -o bom.xml || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-artifacts
          path: |
            bom.xml
            bandit.sarif
            coverage.xml
